export const FETCH_USER = "FETCH_USER";
export const FETCH_SURVEYS = "FETCH_SURVEYS";
export const FETCH_SURVEY = "FETCH_SURVEY";
export const CREATE_SURVEY = "CREATE_SURVEY";
export const DELETE_SURVEY = "DELETE_SURVEY";
export const PROCESSING_SURVEY_REQUEST = "PROCESSING_SURVEY_REQUEST";
export const PROCESSING_SURVEY_FAILURE = "PROCESSING_SURVEY_FAILURE";
export const UPDATE_USER_CREDITS = "UPDATE_USER_CREDITS";
